### ISSUE TITLE
Create Base Front-End that can interact with MongoDB

### ISSUE THREAD

**Issue by dillonviilo** [ajnatzic/WhatsWrongLouie#16]
Create the user front end. This is the majority of the project.

**Comment by ajnatzic** [comment]
@dillonviilo Since you created the mock-ups of the front-end, I will likely need your help for the next few weeks implementing the designs you have created.

**Comment by Haytyj** [comment]
Successfully linked the Athlete Creation frontend screen. User input from the html file will now create an athlete object and push it to the database.

**Comment by ajnatzic** [comment]
MongoDB Integration on the Athlete Creation screen was successfully demoed by @Haytyj to the sponsors.
