### ISSUE TITLE
Database Integration

### ISSUE THREAD

**Issue by dillonviilo** [ajnatzic/WhatsWrongLouie#18]
Verify that the application is interacting with the web app correctly.

**Comment by Haytyj** [comment]
Expanded on the basic functionality written during Sprint 1 by creating other methods for interacting with the database. 

https://github.com/ajnatzic/WhatsWrongLouie/blob/bug/Main.js

**Comment by ajnatzic** [comment]
Database integration has been successfully set-up using MongoDB.
