### ISSUE TITLE
MongoDB integration

### ISSUE THREAD

**Issue by ajnatzic** [ajnatzic/WhatsWrongLouie#3]
In a team meeting, Dillon stated that he may be able to connect our app to a database using [MongoDB](https://www.mongodb.com/). This database could keep track of email addresses, user info, user states, etc. This epic issue will be home to all issues with MongoDB integration.

**Comment by Haytyj** [comment]
After learning the basics of Node JS and MongoDB. Tyler Successfully implemented basic functionality for connecting and interacting with the database.
